[package]
name = "rust-hello-word"
version = "0.1.0"
authors = ["mozz <mozz1@chinaunicom.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
